packages:
  - apps/*
  - packages/*
nodeLinker: hoisted
autoInstallPeers: true
strictPeerDependencies: false
allowBuilds:
  '@firebase/util': true
  postinstall-postinstall: set this to true or false
  protobufjs: true
patchedDependencies:
  '@react-native-community/datetimepicker': patches/@react-native-community__datetimepicker.patch
  react-native-gesture-handler: patches/react-native-gesture-handler.patch
  react-native-html-to-pdf: patches/react-native-html-to-pdf.patch
  react-native-print: patches/react-native-print.patch
  react-native-reanimated: patches/react-native-reanimated.patch
