import React, { useState, forwardRef } from 'react';
import {
  View,
  Text,
  StyleSheet,
  TextInput,
  Pressable,
  KeyboardAvoidingView,
  Platform,
} from 'react-native';
import { BottomSheetModal } from '@gorhom/bottom-sheet';
import { BottomSheet } from '../ui/BottomSheet';
import { useTheme } from '../../providers/ThemeProvider';
import { haptics } from '../../utils/haptics';
import AppIcon from '../common/AppIcon';
import api from '../../services/api/client';
import { useAuthStore } from '../../stores/auth.store';
import { router } from 'expo-router';

interface QuickAddBottomSheetProps {
  onSuccess?: () => void;
  onClose?: () => void;
}

export const QuickAddBottomSheet = forwardRef<
  BottomSheetModal,
  QuickAddBottomSheetProps
>(({ onSuccess, onClose }, ref) => {
  const theme = useTheme();
  const { user } = useAuthStore();
  const [amount, setAmount] = useState('');
  const [title, setTitle] = useState('');
  const [isLoading, setIsLoading] = useState(false);

  const handleSubmit = async () => {
    if (!amount || isNaN(Number(amount)) || !title.trim()) {
      haptics.error();
      return;
    }

    setIsLoading(true);
    try {
      // Send quick expense to backend
      await api.post('/finance/transactions', {
        type: 'expense',
        amount: Number(amount),
        title: title.trim(),
        category: 'General',
        paymentMethod: 'Cash',
        isAutoGenerated: false,
        splitWith: [],
        date: new Date().toISOString(),
        currency: 'INR',
      });

      haptics.success();
      setAmount('');
      setTitle('');
      onSuccess?.();

      // Route to home to see the transaction
      setTimeout(() => {
        router.replace('/(app)/(tabs)/home');
      }, 300);
    } catch (error) {
      console.error('Failed to create quick expense:', error);
      haptics.error();
    } finally {
      setIsLoading(false);
    }
  };

  return (
    <BottomSheet
      ref={ref}
      snapPoints={['50%']}
      onDismiss={() => {
        setAmount('');
        setTitle('');
        onClose?.();
      }}
      enablePanDownToClose
    >
      <KeyboardAvoidingView
        behavior={Platform.OS === 'ios' ? 'padding' : 'height'}
        style={styles.container}
      >
        <View style={styles.header}>
          <Text style={[styles.title, { color: theme.colors.textPrimary }]}>
            Quick Expense
          </Text>
        </View>

        <View style={styles.inputContainer}>
          <Text
            style={[styles.currency, { color: theme.colors.textSecondary }]}
          >
            ₹
          </Text>
          <TextInput
            style={[styles.amountInput, { color: theme.colors.textPrimary }]}
            placeholder="0.00"
            placeholderTextColor={theme.colors.textTertiary}
            keyboardType="decimal-pad"
            value={amount}
            onChangeText={setAmount}
            autoFocus
          />
        </View>

        <View
          style={[
            styles.titleContainer,
            { backgroundColor: theme.colors.secondaryBg },
          ]}
        >
          <AppIcon name="edit-3" size={20} color={theme.colors.textSecondary} />
          <TextInput
            style={[styles.titleInput, { color: theme.colors.textPrimary }]}
            placeholder="What was this for?"
            placeholderTextColor={theme.colors.textTertiary}
            value={title}
            onChangeText={setTitle}
          />
        </View>

        <Pressable
          style={({ pressed }) => [
            styles.submitButton,
            { backgroundColor: theme.colors.primary },
            pressed && { opacity: 0.8 },
            (!amount || !title) && { opacity: 0.5 },
          ]}
          onPress={handleSubmit}
          disabled={!amount || !title || isLoading}
        >
          <Text style={styles.submitText}>
            {isLoading ? 'Saving...' : 'Save Expense'}
          </Text>
        </Pressable>
      </KeyboardAvoidingView>
    </BottomSheet>
  );
});

const styles = StyleSheet.create({
  container: {
    flex: 1,
    paddingHorizontal: 24,
    paddingBottom: 32,
  },
  header: {
    alignItems: 'center',
    marginBottom: 24,
  },
  title: {
    fontSize: 18,
    fontWeight: '700',
  },
  inputContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 32,
  },
  currency: {
    fontSize: 32,
    fontWeight: '600',
    marginRight: 8,
  },
  amountInput: {
    fontSize: 48,
    fontWeight: '800',
    minWidth: 100,
    textAlign: 'center',
  },
  titleContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 16,
    borderRadius: 16,
    marginBottom: 32,
    gap: 12,
  },
  titleInput: {
    flex: 1,
    fontSize: 16,
    fontWeight: '500',
  },
  submitButton: {
    padding: 18,
    borderRadius: 16,
    alignItems: 'center',
  },
  submitText: {
    color: '#FFF',
    fontSize: 16,
    fontWeight: '700',
  },
});
