// types/finance.types.ts

export interface Transaction {
  _id: string;
  userId: string;
  type:
    | 'income'
    | 'expense'
    | 'transfer'
    | 'trip_expense'
    | 'settlement_paid'
    | 'settlement_received';
  amount: number;
  currency: string;
  title: string;
  category: string;
  date: string;
  paymentMethod: 'Cash' | 'Card' | 'UPI' | 'Net Banking' | 'Wallet' | 'Other';
  notes?: string;
  receiptImage?: string;
  tags: string[];
  tripId?: string;
  tripName?: string;
  isAutoGenerated: boolean;
  myShare?: number;
  totalExpenseAmount?: number;
  splitWith?: string[];
  isDeleted: boolean;
  createdAt: string;
  updatedAt: string;
}

export interface Budget {
  _id: string;
  userId: string;
  month: string;
  totalBudget: number;
  totalSpent: number;
  categoryBudgets: {
    category: string;
    amount: number;
    spent: number;
    color?: string;
  }[];
  isActive: boolean;
}

export interface Bill {
  _id: string;
  userId: string;
  title: string;
  amount: number;
  currency: string;
  dueDate: string;
  frequency: 'daily' | 'weekly' | 'monthly' | 'yearly';
  category: string;
  autoPay: boolean;
  isActive: boolean;
  isPaid: boolean;
  paidThisMonth: boolean;
  paidAmount?: number;
  lastPaidDate?: string;
  nextDueDate?: string;
  reminderDays: number;
  notes?: string;
}

export interface Goal {
  _id: string;
  userId: string;
  title: string;
  description?: string;
  targetAmount: number;
  savedAmount: number;
  currency: string;
  targetDate: string;
  category: string;
  icon?: string;
  color?: string;
  isCompleted: boolean;
  progress: number;
  monthlyContribution?: number;
}

export interface DebtSummary {
  totalOwed: number;
  totalOwing: number;
  pendingOwed: number;
  pendingOwing: number;
  byTrip: {
    tripId: string;
    tripName: string;
    owed: number;
    owing: number;
    pendingOwed: number;
    pendingOwing: number;
  }[];
  byUser: {
    userId: string;
    name: string;
    owes: number;
    owed: number;
    net: number;
  }[];
}

export interface DashboardData {
  monthlyOverview: {
    month: string;
    totalIncome: number;
    totalExpense: number;
    netSavings: number;
    budget: number;
    budgetSpent: number;
    budgetRemaining: number;
    budgetUsedPercent: number;
    averageDailyExpense: number;
    tripExpenses: number;
    manualExpenses: number;
    settlementsPaid: number;
    settlementsReceived: number;
    comparedToLastMonth: {
      expensesChange: number;
      incomeChange: number;
      savingsChange: number;
    };
  };
  categoryBreakdown: {
    category: string;
    spent: number;
    budget: number;
    budgetRemaining: number;
    percentOfTotal: number;
    isOverBudget: boolean;
  }[];
  topSpendingCategory: {
    category: string;
    amount: number;
    percentOfTotal: number;
  };
  recentTransactions: Transaction[];
  goals: {
    active: number;
    completed: number;
    items: Goal[];
    totalTarget: number;
    totalSaved: number;
  };
  bills: {
    total: number;
    upcoming: Bill[];
    upcomingCount: number;
    totalDueThisMonth: number;
  };
  stats: {
    transactionCount: number;
    daysWithExpenses: number;
  };
}

// // types/finance.types.ts
// export type TransactionType = 'income' | 'expense' | 'transfer';
// export type PaymentMethod = 'Cash' | 'Card' | 'UPI' | 'Net Banking' | 'Other';
// export type RecurringFrequency = 'weekly' | 'monthly' | 'yearly';

// export interface Transaction {
//   _id: string;
//   userId: string;
//   type: TransactionType;
//   amount: number;
//   currency: string;
//   title: string;
//   category: string;
//   date: string;
//   time?: string;
//   paymentMethod: PaymentMethod;
//   notes?: string;
//   receiptImage?: string;
//   tags: string[];
//   isRecurring: boolean;
//   recurringFrequency?: RecurringFrequency;
//   tripId?: {
//     _id: string;
//     title: string;
//     coverImage: string;
//   };
//   location?: {
//     latitude: number;
//     longitude: number;
//     name: string;
//   };
//   createdAt: string;
//   updatedAt: string;
// }

// export interface CategoryBudget {
//   category: string;
//   amount: number;
//   spent: number;
// }

// export interface Budget {
//   _id: string;
//   userId: string;
//   month: string;
//   totalBudget: number;
//   categoryBudgets: CategoryBudget[];
//   createdAt: string;
//   updatedAt: string;
// }

// export interface Bill {
//   _id: string;
//   userId: string;
//   title: string;
//   amount: number;
//   dueDate: string;
//   frequency: RecurringFrequency;
//   category: string;
//   autoPay: boolean;
//   isActive: boolean;
//   paidThisMonth: boolean;
//   lastPaidDate?: string;
//   createdAt: string;
//   updatedAt: string;
// }

// export interface Goal {
//   _id: string;
//   userId: string;
//   title: string;
//   targetAmount: number;
//   savedAmount: number;
//   targetDate: string;
//   isCompleted: boolean;
//   progress: number;
//   createdAt: string;
//   updatedAt: string;
// }

// export interface MonthlyOverview {
//   totalExpense: number;
//   totalIncome: number;
//   savings: number;
//   budget: number;
//   budgetUsedPercentage: number;
// }

// export interface DashboardData {
//   monthlyOverview: MonthlyOverview;
//   categorySpending: {
//     category: string;
//     spent: number;
//     budget: number;
//   }[];
//   recentTransactions: Transaction[];
//   goals: Goal[];
//   bills: Bill[];
//   stats: {
//     transactionCount: number;
//     expenseCount: number;
//     incomeCount: number;
//     averageDailyExpense: number;
//   };
// }

// export interface TransactionFilters {
//   type?: TransactionType;
//   category?: string;
//   month?: string;
//   startDate?: string;
//   endDate?: string;
//   limit?: number;
//   page?: number;
// }

// export interface BudgetInput {
//   month: string;
//   totalBudget: number;
//   categoryBudgets: { category: string; amount: number }[];
// }
