import { Linking, Platform } from 'react-native';

/**
 * Attempts to open a UPI deep link. 
 * On Android, it tries to use direct intents for popular apps (GPay, PhonePe, Paytm)
 * to ensure a reliable user experience, before falling back to the standard `upi://` scheme.
 * 
 * @param upiDeepLink The `upi://pay?...` link generated by the backend.
 */
export const openUPIApp = async (upiDeepLink: string) => {
    if (!upiDeepLink) return;

    if (Platform.OS === 'android') {
        const apps = [
            'com.google.android.apps.nbu.paisa.user', // Google Pay
            'com.phonepe.app',                         // PhonePe
            'net.one97.paytm',                         // Paytm
        ];

        for (const packageName of apps) {
            try {
                const intentUrl = `intent://pay?${upiDeepLink.split('?')[1]}#Intent;scheme=upi;package=${packageName};end`;
                const supported = await Linking.canOpenURL(intentUrl);
                if (supported) {
                    await Linking.openURL(intentUrl);
                    return;
                }
            } catch (error) {
                // Ignore error and try the next app or fallback
            }
        }
    }

    // Fallback: standard universal UPI link (Works on iOS and Android if registered)
    try {
        const supported = await Linking.canOpenURL(upiDeepLink);
        if (supported) {
            await Linking.openURL(upiDeepLink);
        } else {
            // Force open on Web/Fallback if canOpenURL is restricted
            Linking.openURL(upiDeepLink).catch(() => {});
        }
    } catch (e) {
        Linking.openURL(upiDeepLink).catch(() => {});
    }
};
