// components/ui/TransactionCard.tsx
import React, { useMemo } from 'react';
import {
  View,
  Text,
  StyleSheet,
  Pressable,
  Platform,
  Image,
} from 'react-native';
import { format, isToday, isYesterday, isThisYear } from 'date-fns';
import { GlassCard } from '../ui/GlassCard';
import AppIcon from '../common/AppIcon';
import { useTheme } from '../../providers/ThemeProvider';
import type { Theme } from '../../theme';

type WebPressableState = { hovered?: boolean; pressed?: boolean };

interface TransactionCardProps {
  transaction: {
    _id: string;
    type:
      | 'expense'
      | 'trip_expense'
      | 'income'
      | 'lent'
      | 'borrowed'
      | 'repayment'
      | string;
    amount: number;
    currency: string;
    title: string;
    category: string;
    date: string;
    paymentMethod?: string;
    notes?: string;
    tags?: string[];
    tripId?: {
      _id: string;
      title: string;
      coverImage?: string;
    };
    tripName?: string;
    myShare?: number;
    totalExpenseAmount?: number;
    isAutoGenerated?: boolean;
    relationshipId?: string;
    personName?: string;
    personPhone?: string;
    personUserId?: string;
  };
  onPress?: () => void;
  style?: any;
}

const AMBER = '#F59E0B';
const PINK = '#EC4899';
const BLUE = '#2563EB';

// ─── Helpers ─────────────────────────────────────────────────
/** Alpha for #rgb / #rrggbb / rgb() colours; returns the input untouched otherwise. */
function withAlpha(color: string, alpha: number): string {
  if (color.startsWith('#')) {
    let hex = color.slice(1);
    if (hex.length === 3)
      hex = hex
        .split('')
        .map(c => c + c)
        .join('');
    if (hex.length >= 6) {
      const a = Math.round(alpha * 255)
        .toString(16)
        .padStart(2, '0');
      return `#${hex.slice(0, 6)}${a}`;
    }
  }
  const rgb = color.match(/^rgba?\((\d+),\s*(\d+),\s*(\d+)/);
  if (rgb) return `rgba(${rgb[1]}, ${rgb[2]}, ${rgb[3]}, ${alpha})`;
  return color;
}

function formatWhen(iso?: string): string {
  if (!iso) return '';
  const d = new Date(iso);
  if (isNaN(d.getTime())) return '';
  const time = format(d, 'h:mm a');
  if (isToday(d)) return `Today, ${time}`;
  if (isYesterday(d)) return `Yesterday, ${time}`;
  return isThisYear(d)
    ? `${format(d, 'MMM d')}, ${time}`
    : format(d, 'MMM d, yyyy');
}

function categoryIcon(category: string, type: string): string {
  if (type === 'lent') return 'arrow-up-right';
  if (type === 'borrowed') return 'arrow-down-left';
  if (type === 'repayment') return 'check-circle';
  const cat = category?.toLowerCase() || '';
  if (
    cat.includes('food') ||
    cat.includes('dessert') ||
    cat.includes('desert') ||
    cat.includes('restaurant')
  )
    return 'coffee';
  if (
    cat.includes('travel') ||
    cat.includes('trip') ||
    cat.includes('transport')
  )
    return 'map-pin';
  if (cat.includes('shop')) return 'shopping-bag';
  if (cat.includes('health') || cat.includes('medic')) return 'heart';
  if (cat.includes('entertain') || cat.includes('movie')) return 'film';
  if (cat.includes('cash') || cat.includes('pay') || cat.includes('upi'))
    return 'credit-card';
  if (cat.includes('income') || cat.includes('salary')) return 'dollar-sign';
  return 'tag';
}

const TYPE_LABEL: Record<string, string> = {
  expense: 'Expense',
  trip_expense: 'Trip expense',
  income: 'Income',
  lent: 'Lent',
  borrowed: 'Borrowed',
  repayment: 'Repaid',
};

// ─── Component ───────────────────────────────────────────────
export function TransactionCard({
  transaction,
  onPress,
  style,
}: TransactionCardProps) {
  const theme = useTheme();
  const styles = useMemo(() => createStyles(theme), [theme]);

  const type = transaction.type;
  const isTrip = type === 'trip_expense';
  const isIncome = type === 'income';
  const isLent = type === 'lent';
  const isBorrowed = type === 'borrowed';
  const isRepayment = type === 'repayment';
  const isPositive = isIncome || isBorrowed;

  const symbol =
    transaction.currency === 'INR' ? '₹' : `${transaction.currency} `;
  const amountText = `${isPositive ? '+' : '−'}${symbol}${Number(transaction.amount || 0).toLocaleString('en-IN')}`;
  const when = formatWhen(transaction.date);
  const tripName = transaction.tripName || transaction.tripId?.title;
  const cover = isTrip ? transaction.tripId?.coverImage : undefined;
  const typeLabel = TYPE_LABEL[type] || 'Expense';

  // Accent drives the side bar, the leading badge and the status pill.
  const accent =
    isIncome || isRepayment
      ? theme.colors.success
      : isTrip
        ? BLUE
        : isLent
          ? AMBER
          : isBorrowed
            ? PINK
            : theme.colors.primary;

  // Amount pill: coloured for inflows / lent, neutral for everyday spending.
  const amountTone: string | null = isPositive
    ? theme.colors.success
    : isLent
      ? AMBER
      : null;
  const neutralTint = theme.isDark
    ? 'rgba(255,255,255,0.08)'
    : 'rgba(15,23,42,0.06)';

  const showShare =
    isTrip &&
    transaction.myShare !== undefined &&
    transaction.myShare !== transaction.amount;

  const icon = categoryIcon(transaction.category, type);
  const plainExpense =
    !isIncome && !isLent && !isBorrowed && !isRepayment && !isTrip;

  return (
    <Pressable
      onPress={onPress}
      accessibilityRole="button"
      accessibilityLabel={`${transaction.title}, ${amountText}, ${typeLabel}${when ? `, ${when}` : ''}`}
      style={({ hovered, pressed }: WebPressableState) => [
        styles.container,
        Platform.OS === 'web' && hovered && styles.hover,
        pressed && { opacity: 0.92 },
        style,
      ]}
    >
      <GlassCard
        style={styles.card}
        intensity={theme.isDark ? 15 : 8}
        padding="none"
      >
        <View style={[styles.accentBar, { backgroundColor: accent }]} />

        <View style={styles.inner}>
          {/* Leading visual: trip cover with an icon badge, or a tinted tile */}
          <View style={styles.lead}>
            {cover ? (
              <>
                <Image source={{ uri: cover }} style={styles.leadImage} />
                <View
                  style={[
                    styles.leadBadge,
                    {
                      backgroundColor: accent,
                      borderColor: theme.colors.surface,
                    },
                  ]}
                >
                  <AppIcon name={icon as any} size={11} color="#FFFFFF" />
                </View>
              </>
            ) : (
              <View
                style={[
                  styles.leadTile,
                  { backgroundColor: withAlpha(accent, 0.13) },
                ]}
              >
                <AppIcon name={icon as any} size={20} color={accent} />
              </View>
            )}
          </View>

          <View style={styles.body}>
            {/* Title + amount */}
            <View style={styles.titleRow}>
              <View style={styles.titleWrap}>
                <Text
                  style={[styles.title, { color: theme.colors.textPrimary }]}
                  numberOfLines={1}
                >
                  {transaction.title}
                </Text>
                <View style={styles.metaRow}>
                  <AppIcon
                    name="calendar"
                    size={12}
                    color={theme.colors.textTertiary}
                  />
                  <Text
                    style={[styles.meta, { color: theme.colors.textTertiary }]}
                    numberOfLines={1}
                  >
                    {when}
                    {transaction.category ? ` • ${transaction.category}` : ''}
                  </Text>
                </View>
              </View>

              <View style={styles.amountCol}>
                <View
                  style={[
                    styles.amountPill,
                    {
                      backgroundColor: amountTone
                        ? withAlpha(amountTone, 0.14)
                        : neutralTint,
                    },
                  ]}
                >
                  <Text
                    style={[
                      styles.amount,
                      { color: amountTone || theme.colors.textPrimary },
                    ]}
                    numberOfLines={1}
                  >
                    {amountText}
                  </Text>
                </View>
                {showShare && (
                  <Text
                    style={[styles.share, { color: theme.colors.textTertiary }]}
                    numberOfLines={1}
                  >
                    Your share {symbol}
                    {Number(transaction.myShare).toLocaleString('en-IN')}
                  </Text>
                )}
              </View>
            </View>

            {/* Chips + chevron */}
            <View style={styles.chipsRow}>
              <View style={styles.chips}>
                <View
                  style={[
                    styles.statusPill,
                    {
                      backgroundColor: plainExpense
                        ? neutralTint
                        : withAlpha(accent, 0.13),
                    },
                  ]}
                >
                  <View
                    style={[
                      styles.dot,
                      {
                        backgroundColor: plainExpense
                          ? theme.colors.textTertiary
                          : accent,
                      },
                    ]}
                  />
                  <Text
                    style={[
                      styles.statusText,
                      {
                        color: plainExpense
                          ? theme.colors.textSecondary
                          : accent,
                      },
                    ]}
                  >
                    {typeLabel}
                  </Text>
                </View>

                {transaction.personName ? (
                  <View style={[styles.chip, { backgroundColor: neutralTint }]}>
                    <AppIcon
                      name="user"
                      size={11}
                      color={theme.colors.textSecondary}
                    />
                    <Text
                      style={[
                        styles.chipText,
                        { color: theme.colors.textSecondary },
                      ]}
                      numberOfLines={1}
                    >
                      {transaction.personName}
                    </Text>
                  </View>
                ) : null}

                {tripName ? (
                  <View
                    style={[
                      styles.chip,
                      { backgroundColor: neutralTint, flexShrink: 1 },
                    ]}
                  >
                    <AppIcon
                      name="map-pin"
                      size={11}
                      color={theme.colors.textSecondary}
                    />
                    <Text
                      style={[
                        styles.chipText,
                        { color: theme.colors.textSecondary },
                      ]}
                      numberOfLines={1}
                    >
                      {tripName}
                    </Text>
                  </View>
                ) : null}

                {transaction.paymentMethod ? (
                  <View style={[styles.chip, { backgroundColor: neutralTint }]}>
                    <AppIcon
                      name="credit-card"
                      size={11}
                      color={theme.colors.textSecondary}
                    />
                    <Text
                      style={[
                        styles.chipText,
                        { color: theme.colors.textSecondary },
                      ]}
                      numberOfLines={1}
                    >
                      {transaction.paymentMethod}
                    </Text>
                  </View>
                ) : null}
              </View>

              <AppIcon
                name="chevron-right"
                size={16}
                color={theme.colors.textTertiary}
              />
            </View>

            {transaction.notes ? (
              <View
                style={[
                  styles.notesRow,
                  { borderTopColor: theme.colors.borderLight },
                ]}
              >
                <Text
                  style={[styles.notes, { color: theme.colors.textSecondary }]}
                  numberOfLines={1}
                >
                  {transaction.notes}
                </Text>
              </View>
            ) : null}
          </View>
        </View>
      </GlassCard>
    </Pressable>
  );
}

// ─── Styles ──────────────────────────────────────────────────
function createStyles(theme: Theme) {
  const hairline = theme.isDark
    ? 'rgba(255,255,255,0.08)'
    : 'rgba(15,23,42,0.07)';

  return StyleSheet.create({
    // Spacing between cards is handled by the grid that renders them.
    container: { width: '100%' },
    hover: {
      transform: [{ translateY: -2 }],
      ...Platform.select({
        web: { transition: 'transform 0.15s ease' } as any,
      }),
    },
    card: {
      borderRadius: 20,
      borderWidth: 1,
      borderColor: hairline,
      overflow: 'hidden',
      width: '100%',
    },
    accentBar: { position: 'absolute', left: 0, top: 0, bottom: 0, width: 4 },
    inner: {
      flexDirection: 'row',
      alignItems: 'flex-start',
      gap: 12,
      paddingVertical: 14,
      paddingLeft: 18,
      paddingRight: 14,
    },

    lead: { width: 52, height: 52 },
    leadImage: { width: 52, height: 52, borderRadius: 16 },
    leadTile: {
      width: 52,
      height: 52,
      borderRadius: 16,
      alignItems: 'center',
      justifyContent: 'center',
    },
    leadBadge: {
      position: 'absolute',
      left: -6,
      bottom: -6,
      width: 24,
      height: 24,
      borderRadius: 12,
      borderWidth: 2,
      alignItems: 'center',
      justifyContent: 'center',
    },

    body: { flex: 1, minWidth: 0, gap: 10 },
    titleRow: { flexDirection: 'row', alignItems: 'flex-start', gap: 10 },
    titleWrap: { flex: 1, minWidth: 0, gap: 3 },
    title: { fontSize: 15, fontWeight: '800', letterSpacing: -0.3 },
    metaRow: { flexDirection: 'row', alignItems: 'center', gap: 5 },
    meta: {
      fontSize: 12,
      fontWeight: '500',
      flexShrink: 1,
      textTransform: 'none',
    },

    amountCol: { alignItems: 'flex-end', gap: 3, flexShrink: 0 },
    amountPill: {
      paddingHorizontal: 12,
      paddingVertical: 5,
      borderRadius: 999,
    },
    amount: { fontSize: 14, fontWeight: '800', letterSpacing: -0.3 },
    share: { fontSize: 11, fontWeight: '500' },

    chipsRow: { flexDirection: 'row', alignItems: 'center', gap: 8 },
    chips: {
      flex: 1,
      flexDirection: 'row',
      flexWrap: 'wrap',
      alignItems: 'center',
      gap: 6,
    },
    statusPill: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 5,
      paddingHorizontal: 9,
      paddingVertical: 4,
      borderRadius: 999,
    },
    dot: { width: 6, height: 6, borderRadius: 3 },
    statusText: { fontSize: 11.5, fontWeight: '700' },
    chip: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 4,
      paddingHorizontal: 8,
      paddingVertical: 4,
      borderRadius: 999,
      maxWidth: '100%',
    },
    chipText: { fontSize: 11.5, fontWeight: '600', flexShrink: 1 },

    notesRow: { borderTopWidth: StyleSheet.hairlineWidth, paddingTop: 8 },
    notes: { fontSize: 12, fontWeight: '500', fontStyle: 'italic' },
  });
}
// import React, { useMemo } from 'react';
// import { View, Text, StyleSheet, Pressable, Platform, Image } from 'react-native';
// import { format } from 'date-fns';
// import { GlassCard } from '../ui/GlassCard';
// import AppIcon from '../common/AppIcon';
// import { Badge } from '../ui/Badge';
// import { useTheme } from '../../providers/ThemeProvider';

// type WebPressableState = { hovered?: boolean; pressed?: boolean };

// interface TransactionCardProps {
//     transaction: {
//         _id: string;
//         type: 'expense' | 'trip_expense' | 'income' | 'lent' | 'borrowed' | 'repayment' | string;
//         amount: number;
//         currency: string;
//         title: string;
//         category: string;
//         date: string;
//         paymentMethod?: string;
//         notes?: string;
//         tags?: string[];
//         tripId?: {
//             _id: string;
//             title: string;
//             coverImage?: string;
//         };
//         tripName?: string;
//         myShare?: number;
//         totalExpenseAmount?: number;
//         isAutoGenerated?: boolean;
//         relationshipId?: string;
//         personName?: string;
//         personPhone?: string;
//         personUserId?: string;
//     };
//     onPress?: () => void;
//     style?: any;
// }

// export function TransactionCard({ transaction, onPress, style }: TransactionCardProps) {
//     const theme = useTheme();
//     const styles = useStyles();

//     const isTripExpense = transaction.type === 'trip_expense';
//     const isIncome = transaction.type === 'income';
//     const isLent = transaction.type === 'lent';
//     const isBorrowed = transaction.type === 'borrowed';
//     const isRepayment = transaction.type === 'repayment';
//     const isPositiveCashflow = isIncome || isBorrowed;

//     const currencySymbol = transaction.currency === 'INR' ? '₹' : transaction.currency + ' ';
//     const formattedDate = transaction.date ? format(new Date(transaction.date), 'MMM d, yyyy • h:mm a') : '';

//     const getCategoryIcon = (category: string) => {
//         if (isLent) return 'arrow-up-right';
//         if (isBorrowed) return 'arrow-down-left';
//         if (isRepayment) return 'check-circle';
//         const cat = category?.toLowerCase() || '';
//         if (cat.includes('food') || cat.includes('desert') || cat.includes('restaurant')) return 'coffee';
//         if (cat.includes('travel') || cat.includes('trip') || cat.includes('transport')) return 'map-pin';
//         if (cat.includes('cash') || cat.includes('pay') || cat.includes('upi')) return 'credit-card';
//         if (cat.includes('income') || cat.includes('salary')) return 'dollar-sign';
//         return 'tag';
//     };

//     const accentColor = isIncome || isRepayment
//         ? theme.colors.success
//         : isTripExpense
//             ? '#2563EB'
//             : isLent
//                 ? '#F59E0B'
//                 : isBorrowed
//                     ? '#EC4899'
//                     : theme.colors.primary;

//     return (
//         <Pressable
//             onPress={onPress}
//             style={({ hovered }: WebPressableState) => [
//                 styles.container,
//                 Platform.OS === 'web' && hovered && styles.hoverLift,
//                 style
//             ]}
//         >
//             <GlassCard style={styles.card} intensity={theme.isDark ? 15 : 8}>
//                 {/* Left Accent Bar */}
//                 <View style={[styles.accentBar, { backgroundColor: accentColor }]} />

//                 <View style={styles.cardInner}>
//                     <View style={styles.topRow}>
//                         <View style={[
//                             styles.iconBox,
//                             {
//                                 backgroundColor: isTripExpense
//                                     ? theme.colors.secondaryBg
//                                     : isLent
//                                     ? '#FEF3C7'
//                                     : isBorrowed
//                                     ? '#FCE7F3'
//                                     : isRepayment
//                                     ? '#D1FAE5'
//                                     : theme.colors.primaryBg,
//                                 borderColor: isTripExpense
//                                     ? theme.colors.secondary + '33'
//                                     : isLent
//                                     ? '#F59E0B44'
//                                     : isBorrowed
//                                     ? '#EC489944'
//                                     : isRepayment
//                                     ? '#10B98144'
//                                     : theme.colors.borderLight
//                             }
//                         ]}>
//                             {isTripExpense && transaction.tripId?.coverImage ? (
//                                 <Image source={{ uri: transaction.tripId.coverImage }} style={styles.tripThumb} />
//                             ) : (
//                                 <AppIcon
//                                     name={getCategoryIcon(transaction.category)}
//                                     size={16}
//                                     color={isTripExpense ? theme.colors.secondary : accentColor}
//                                 />
//                             )}
//                         </View>

//                         <View style={styles.titleWrap}>
//                             <View style={{ flexDirection: 'row', alignItems: 'center', gap: 6, flexWrap: 'wrap' }}>
//                                 <Text style={[styles.title, { color: theme.colors.textPrimary }]} numberOfLines={1}>
//                                     {transaction.title}
//                                 </Text>
//                                 {isTripExpense && (
//                                     <Badge label="TRIP" variant="primary" />
//                                 )}
//                                 {isIncome && (
//                                     <Badge label="INCOME" variant="success" />
//                                 )}
//                                 {isLent && (
//                                     <Badge label="LENT" variant="warning" />
//                                 )}
//                                 {isBorrowed && (
//                                     <Badge label="BORROWED" variant="danger" />
//                                 )}
//                                 {isRepayment && (
//                                     <Badge label="REPAID" variant="success" />
//                                 )}
//                             </View>
//                             <Text style={[styles.subtitle, { color: theme.colors.textSecondary }]} numberOfLines={1}>
//                                 {transaction.personName ? `With: ${transaction.personName} • ` : ''}
//                                 {transaction.category} {transaction.paymentMethod ? `• ${transaction.paymentMethod}` : ''}
//                             </Text>
//                         </View>

//                         <View style={styles.amountWrap}>
//                             <Text style={[
//                                 styles.amount,
//                                 {
//                                     color: isPositiveCashflow
//                                         ? theme.colors.success
//                                         : isLent
//                                         ? '#F59E0B'
//                                         : theme.colors.textPrimary
//                                 }
//                             ]}>
//                                 {isPositiveCashflow ? '+' : '−'}{currencySymbol}{transaction.amount.toLocaleString('en-IN')}
//                             </Text>
//                             {isTripExpense && transaction.myShare !== undefined && transaction.myShare !== transaction.amount && (
//                                 <Text style={[styles.shareText, { color: theme.colors.textSecondary }]}>
//                                     Share: {currencySymbol}{transaction.myShare.toLocaleString('en-IN')}
//                                 </Text>
//                             )}
//                         </View>
//                     </View>

//                     {/* Trip Pill Location Banner (Only for trip expenses) */}
//                     {isTripExpense && (transaction.tripName || transaction.tripId?.title) && (
//                         <View style={[styles.tripBanner, { backgroundColor: theme.colors.overlayLight, borderColor: theme.colors.borderLight }]}>
//                             <AppIcon name="map-pin" size={11} color={theme.colors.secondary} />
//                             <Text style={[styles.tripBannerText, { color: theme.colors.textSecondary }]} numberOfLines={1}>
//                                 {transaction.tripName || transaction.tripId?.title}
//                             </Text>
//                         </View>
//                     )}

//                     <View style={[styles.footerRow, { borderTopColor: theme.colors.borderLight }]}>
//                         <Text style={[styles.dateText, { color: theme.colors.textTertiary }]}>
//                             {formattedDate}
//                         </Text>
//                         <Text style={[styles.notesText, { color: theme.colors.textSecondary }]} numberOfLines={1}>
//                             {transaction.notes ? `"${transaction.notes}"` : ''}
//                         </Text>
//                     </View>
//                 </View>
//             </GlassCard>
//         </Pressable>
//     );
// }

// const useStyles = () => {
//     const theme = useTheme();
//     return useMemo(() => StyleSheet.create({
//         container: {
//             width: '100%',
//             marginBottom: 8,
//         },
//         hoverLift: {
//             transform: [{ translateY: -2 }],
//         },
//         card: {
//             borderRadius: 16,
//             borderWidth: 1,
//             borderColor: 'rgba(255,255,255,0.06)',
//             overflow: 'hidden',
//             width: '100%',
//         },
//         accentBar: {
//             position: 'absolute',
//             left: 0,
//             top: 0,
//             bottom: 0,
//             width: 3.5,
//         },
//         cardInner: {
//             padding: 12,
//             paddingLeft: 16,
//             justifyContent: 'space-between',
//         },
//         topRow: {
//             flexDirection: 'row',
//             alignItems: 'center',
//             gap: 10,
//         },
//         iconBox: {
//             width: 38,
//             height: 38,
//             borderRadius: 12,
//             alignItems: 'center',
//             justifyContent: 'center',
//             overflow: 'hidden',
//             borderWidth: 1,
//         },
//         tripThumb: {
//             width: '100%',
//             height: '100%',
//             resizeMode: 'cover',
//         },
//         titleWrap: {
//             flex: 1,
//         },
//         title: {
//             fontSize: 14,
//             fontWeight: '800',
//             letterSpacing: -0.2,
//             flexShrink: 1,
//         },
//         subtitle: {
//             fontSize: 11.5,
//             fontWeight: '600',
//             marginTop: 2,
//             textTransform: 'capitalize',
//         },
//         amountWrap: {
//             alignItems: 'flex-end',
//         },
//         amount: {
//             fontSize: 15,
//             fontWeight: '900',
//             letterSpacing: -0.3,
//         },
//         shareText: {
//             fontSize: 10.5,
//             fontWeight: '600',
//             marginTop: 1,
//         },
//         tripBanner: {
//             flexDirection: 'row',
//             alignItems: 'center',
//             gap: 5,
//             marginTop: 8,
//             paddingHorizontal: 8,
//             paddingVertical: 4,
//             borderRadius: 8,
//             borderWidth: 1,
//         },
//         tripBannerText: {
//             fontSize: 11.5,
//             fontWeight: '700',
//         },
//         footerRow: {
//             flexDirection: 'row',
//             justifyContent: 'space-between',
//             alignItems: 'center',
//             marginTop: 8,
//             paddingTop: 8,
//             borderTopWidth: 1,
//         },
//         dateText: {
//             fontSize: 10.5,
//             fontWeight: '600',
//         },
//         notesText: {
//             fontSize: 10.5,
//             fontStyle: 'italic',
//             maxWidth: '55%',
//         },
//     }), [theme]);
// };
