// services/api/finance.api.ts

import { apiClient, ApiResponse } from './client';

export const financeApi = {
  // ─────────────────────────────────────────────────────────────
  // DASHBOARD & ANALYTICS
  // ─────────────────────────────────────────────────────────────

  getDashboard: (params?: {
    month?: string;
    includeTripExpenses?: boolean;
  }) => {
    return apiClient.get('/finance/dashboard', { params });
  },

  getAnalytics: (params?: {
    period?: 'week' | 'month' | 'quarter' | 'year' | 'all';
    startDate?: string;
    endDate?: string;
    category?: string;
    type?: 'income' | 'expense' | 'all';
  }) => {
    return apiClient.get('/finance/analytics', { params });
  },

  getSpendingTrends: (params?: { months?: number; category?: string }) => {
    return apiClient.get('/finance/trends', { params });
  },

  syncTripExpenses: (tripId?: string) => {
    return apiClient.post('/finance/sync-trips', { tripId });
  },

  getSpendingStreak: () => {
    return apiClient.get<
      ApiResponse<{
        currentStreak: number;
        longestStreak: number;
        isActive: boolean;
      }>
    >('/finance/streak');
  },

  // ─────────────────────────────────────────────────────────────
  // TRANSACTIONS
  // ─────────────────────────────────────────────────────────────

  getTransactions: (params?: {
    type?:
      | 'income'
      | 'expense'
      | 'transfer'
      | 'trip_expense'
      | 'settlement_paid'
      | 'settlement_received'
      | 'all';
    category?: string;
    month?: string;
    startDate?: string;
    endDate?: string;
    limit?: number;
    page?: number;
    search?: string;
    tags?: string[];
    tripId?: string;
    isAutoGenerated?: boolean;
    sortBy?: string;
    sortOrder?: 'asc' | 'desc';
  }) => {
    return apiClient.get('/finance/transactions', { params });
  },

  getTransactionById: (id: string) => {
    return apiClient.get(`/finance/transactions/${id}`);
  },

  createTransaction: (data: {
    type: 'income' | 'expense' | 'transfer';
    amount: number;
    currency?: string;
    title: string;
    category: string;
    date?: string;
    paymentMethod?:
      'Cash' | 'Card' | 'UPI' | 'Net Banking' | 'Wallet' | 'Other';
    notes?: string;
    receiptImage?: string;
    tags?: string[];
    isRecurring?: boolean;
    recurringFrequency?: 'daily' | 'weekly' | 'monthly' | 'yearly';
    recurringEndDate?: string;
    location?: { latitude?: number; longitude?: number; name?: string };
  }) => {
    return apiClient.post('/finance/transactions', data);
  },

  updateTransaction: (id: string, data: any) => {
    return apiClient.put(`/finance/transactions/${id}`, data);
  },

  deleteTransaction: (id: string, permanent?: boolean) => {
    return apiClient.delete(`/finance/transactions/${id}`, {
      params: { permanent },
    });
  },

  restoreTransaction: (id: string) => {
    return apiClient.post(`/finance/transactions/${id}/restore`);
  },

  bulkDeleteTransactions: (ids: string[]) => {
    return apiClient.post('/finance/transactions/bulk-delete', { ids });
  },

  // ─────────────────────────────────────────────────────────────
  // BUDGET
  // ─────────────────────────────────────────────────────────────

  getBudget: (params?: { month?: string }) => {
    return apiClient.get('/finance/budget', { params });
  },

  setBudget: (data: {
    month: string;
    totalBudget: number;
    categoryBudgets: { category: string; amount: number; color?: string }[];
  }) => {
    return apiClient.post('/finance/budget', data);
  },

  updateBudget: (id: string, data: any) => {
    return apiClient.put(`/finance/budget/${id}`, data);
  },

  deleteBudget: (id: string) => {
    return apiClient.delete(`/finance/budget/${id}`);
  },

  getBudgetCategories: () => {
    return apiClient.get('/finance/budget/categories');
  },

  // ─────────────────────────────────────────────────────────────
  // BILLS & SUBSCRIPTIONS
  // ─────────────────────────────────────────────────────────────

  getBills: (params?: {
    isActive?: boolean;
    category?: string;
    upcoming?: boolean;
    isPaid?: boolean;
    search?: string;
    dateFilter?: string;
    startDate?: string;
    endDate?: string;
    page?: number;
    limit?: number;
  }) => {
    return apiClient.get('/finance/bills', { params });
  },

  getBillById: (id: string) => {
    return apiClient.get(`/finance/bills/${id}`);
  },

  createBill: (data: {
    title: string;
    amount: number;
    currency?: string;
    dueDate: string;
    frequency: 'daily' | 'weekly' | 'monthly' | 'yearly';
    category: string;
    autoPay?: boolean;
    isActive?: boolean;
    reminderDays?: number;
    notes?: string;
  }) => {
    return apiClient.post('/finance/bills', data);
  },

  updateBill: (id: string, data: any) => {
    return apiClient.put(`/finance/bills/${id}`, data);
  },

  payBill: (id: string, data?: { paidAmount?: number; date?: string }) => {
    return apiClient.post(`/finance/bills/${id}/pay`, data);
  },

  skipBill: (id: string) => {
    return apiClient.post(`/finance/bills/${id}/skip`);
  },

  deleteBill: (id: string) => {
    return apiClient.delete(`/finance/bills/${id}`);
  },

  // ─────────────────────────────────────────────────────────────
  // GOALS & SAVINGS
  // ─────────────────────────────────────────────────────────────

  getGoals: (params?: { isCompleted?: boolean; category?: string }) => {
    return apiClient.get('/finance/goals', { params });
  },

  getGoalById: (id: string) => {
    return apiClient.get(`/finance/goals/${id}`);
  },

  createGoal: (data: {
    title: string;
    description?: string;
    targetAmount: number;
    currency?: string;
    targetDate: string;
    category: string;
    icon?: string;
    color?: string;
    monthlyContribution?: number;
  }) => {
    return apiClient.post('/finance/goals', data);
  },

  updateGoal: (id: string, data: any) => {
    return apiClient.put(`/finance/goals/${id}`, data);
  },

  contributeToGoal: (id: string, data: { amount: number; date?: string }) => {
    return apiClient.post(`/finance/goals/${id}/contribute`, data);
  },

  deleteGoal: (id: string) => {
    return apiClient.delete(`/finance/goals/${id}`);
  },

  // ─────────────────────────────────────────────────────────────
  // DEBT & SETTLEMENT
  // ─────────────────────────────────────────────────────────────

  getDebtSummary: (params?: { includeTrips?: boolean }) => {
    return apiClient.get('/finance/debt/summary', { params });
  },

  getDebtDetails: (params?: {
    userId?: string;
    tripId?: string;
    status?: 'pending' | 'initiated' | 'confirmed' | 'disputed' | 'settled';
    includeTrips?: boolean;
  }) => {
    return apiClient.get('/finance/debt/details', { params });
  },

  createDebt: (data: {
    amount: number;
    type: 'lent' | 'borrowed';
    friendUserId?: string;
    name?: string;
    reason?: string;
    date?: string;
  }) => {
    return apiClient.post('/finance/debt', data);
  },

  settleDebt: (debtId: string) => {
    return apiClient.post(`/finance/debt/${debtId}/settle`);
  },

  // ─────────────────────────────────────────────────────────────
  // CATEGORIES & TAGS
  // ─────────────────────────────────────────────────────────────

  getCategories: (params?: { type?: 'income' | 'expense' }) => {
    return apiClient.get('/finance/categories', { params });
  },

  getTags: () => {
    return apiClient.get('/finance/tags');
  },

  // ─────────────────────────────────────────────────────────────
  // EXPORT & REPORTING
  // ─────────────────────────────────────────────────────────────

  exportTransactions: (params?: {
    startDate?: string;
    endDate?: string;
    format?: 'csv' | 'pdf' | 'excel';
    type?: 'income' | 'expense' | 'all';
  }) => {
    return apiClient.get('/finance/export', { params, responseType: 'blob' });
  },

  getMonthlyReport: (month?: string) => {
    return apiClient.get(
      `/finance/report/monthly${month ? `?month=${month}` : ''}`,
    );
  },

  getYearlyReport: (year?: string) => {
    return apiClient.get(
      `/finance/report/yearly${year ? `?year=${year}` : ''}`,
    );
  },
};
